from typing import Protocol

from app.domain.models import Conversation, Message


class ChatRepository(Protocol):
    def create_conversation(self, user_id: str) -> Conversation: ...

    def get_conversation(self, conversation_id: str, user_id: str) -> Conversation | None: ...

    def add_message(self, message: Message) -> None: ...

    def list_messages(self, conversation_id: str, user_id: str) -> list[Message]: ...

    def get_message(self, message_id: str, user_id: str) -> Message | None: ...
